abacusAccountCount: 1
abacusRseCount: 1
conveyorTransferSubmitterCount: 1
conveyorPollerCount: 1
conveyorFinisherCount: 1
hermesCount: 0
judgeCleanerCount: 1
judgeEvaluatorCount: 1
judgeInjectorCount: 1
judgeRepairerCount: 1
undertakerCount: 1
reaperCount: 1

abacusAccount:
  threads: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "256Mi"
      cpu: "50m"

abacusRse:
  threads: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "256Mi"
      cpu: "50m"

reaper:
  greedy: 1
  threads: 1
  sleepTime: 60
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "100m"
  extraSecretMounts:
    - secretFullName: x509up
      mountPath: /opt/proxy/x509up
      subPath: x509up
  additionalEnvs:
    - name: X509_USER_PROXY
      value: /opt/proxy/x509up

undertaker:
  threads: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "256Mi"
      cpu: "50m"

conveyorTransferSubmitter:
  threads: 1
  sleepTime: 10
  activities: "'Express' 'Functional Test' 'User Subscriptions'"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  extraSecretMounts:
    - secretFullName: x509up
      mountPath: /opt/proxy/x509up
      subPath: x509up
  config:
    conveyor:
      usercert: "/opt/proxy/x509up"

conveyorPoller:
  threads: 1
  sleepTime: 10
  olderThan: 0
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  extraSecretMounts:
    - secretFullName: x509up
      mountPath: /opt/proxy/x509up
      subPath: x509up
  config:
    conveyor:
      usercert: "/opt/proxy/x509up"

conveyorFinisher:
  threads: 1
  sleepTime: 10
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

judgeCleaner:
  threads: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

judgeEvaluator:
  threads: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"


judgeRepairer:
  threads: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"


judgeInjector:
  threads: 1
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"

image:
  tag: latest
  pullPolicy: Always

useDeprecatedImplicitSecrets: false

secretMounts:
  - volumeName: grid-security-ca
    secretFullName: ca-cert
    mountPath: /etc/grid-security/certificates/5fca1cb1.0
    subPath: tls.cert

ftsRenewal:
  enabled: 1
  image:
    repository: rucio/fts-cron
    tag: latest-java
    pullPolicy: Always
  script: "tutorial"
  vos:
    - vo: "tutorial"
      voms: "tutorial"
  servers: "https://fts:8446"
  additionalEnvs:
    - name: "FETCH_CRL"
      value: "False"
    - name: "RUCIO_PROXY_SECRETS"
      value: "x509up"
  secretMounts:
    # The "tutorial" script expects certificates in a very specific, non-configurable, location:
    # https://github.com/rucio/containers/blob/master/fts-cron/renew_fts_proxy_tutorial.sh.j2
    - volumeName: rucio-cert
      secretFullName: hostcert-rucio
      mountPath: /opt/rucio/certs/usercert.pem
      subPath: tls.cert
    - volumeName: rucio-key
      secretFullName: hostcert-rucio
      mountPath: /opt/rucio/keys/userkey.pem
      subPath: tls.key
      defaultMode: 0600
    - volumeName: grid-security-ca
      secretFullName: ca-cert
      mountPath: /etc/grid-security/certificates/rucio_ca.pem
      subPath: tls.cert

config:
  database:
    default: postgresql+psycopg://rucio:secret@postgres-postgresql/rucio
    schema: test

  messaging_hermes:
    username: "hermes"
    password: "supersecret"
    nonssl_port: "61613"
    use_ssl: "False"
    destination: "/queue/events"
    brokers: "activemq"

  conveyor:
    scheme: "gsiftp,root,https,davs"
    transfertool: "fts3"
    ftshosts: "https://fts:8446"
    cacert: "/etc/grid-security/certificates/5fca1cb1.0"

  policy:
    permission: "generic"
    schema: "generic"
    lfn2pfn_algorithm_default: "hash"

  monitor:
    user_scope: "tutorial"
